version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Coder-boop-web/Android---test-site"

[[analyzers]]
name = "test-coverage"